# Generated by Django 5.1.5 on 2025-01-27 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('cedula', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmaciald', models.IntegerField()),
                ('medicamentold', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('actualizarStock', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('rol', models.CharField(choices=[('AD', 'Administrador'), ('EM', 'Empleado'), ('ES', 'Empleado Sucursal'), ('CL', 'Cliente')], default='CL', max_length=2)),
                ('primerNombre', models.CharField(max_length=255)),
                ('primerApellido', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionFC.cliente')),
                ('sucursalCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_compra', to='GestionFC.sucursal')),
                ('sucursalEntrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_entrega', to='GestionFC.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionFC.medicamento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionFC.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionFC.medicamento')),
                ('sucursalDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_destino', to='GestionFC.sucursal')),
                ('sucursalOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_origen', to='GestionFC.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmaciald', models.IntegerField()),
                ('medicamentold', models.IntegerField()),
                ('total', models.FloatField()),
                ('clienteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionFC.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precioUnitario', models.FloatField()),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionFC.venta')),
            ],
        ),
    ]
